config/routes.rb
Rails.application.routes.draw do
  get 'labels/index'
  get 'sessions/new'
  root 'tasks#index'
  resources :tasks do
    collection do
      get :sort
    end
  end
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  namespace :admin do
    resources :users
  end

  resources :labels
end

app/models/task.rb
class Task < ApplicationRecord
  include SearchModule

  validates :title, presence: true
  validates :details, presence: true
  validates :priority, inclusion: { in: %w(A B C D E) }, presence: true
  validates :status, inclusion: { in: %w(未着手 着手中 完了) }, presence: true
  validates :limit, presence: true

  belongs_to :user, foreign_key: "user_id"

  has_many :labellings, dependent: :destroy, foreign_key: 'task_id'
  has_many :labels, through: :labellings, source: :label

  accepts_nested_attributes_for :labellings
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  PER = 10

  def index
    if logged_in?
      @tasks = Task.page(params[:page]).per(PER).where(user_id: current_user.id).desc_sort_create_at
    else
      redirect_to new_session_path
    end
  end

  def sort
    if logged_in?
      @tasks = Task.includes(:labels).references(:labels).page(params[:page]).per(PER).set_sort(params).where(user_id: current_user.id)
      render :index
    else
      redirect_to new_session_path
    end
  end

  def new
    if logged_in? && params[:back]
      @task = Task.new(task_params)
    elsif logged_in?
      @task = Task.new
    else
      redirect_to new_session_path
    end
  end

  def create
    @task = current_user.tasks.build(task_params)
    @task.user_id = current_user.id
    if params[:back]
      render :new
    else
      if @task.save
        flash[:success] = 'タスクを作成しました！'
        redirect_to task_path(@task.id)
      else
        render :new
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    if @task.update(task_params)
      flash[:success] = 'タスクを編集しました！'
      redirect_to tasks_path
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    flash[:success] = 'タスクを削除しました！'
    redirect_to tasks_url
  end

  private

  def set_task
    if logged_in?
      @task = Task.find(params[:id])
      @labels = Label.where("user_id is null or user_id = ?", current_user.id).order(created_at: "DESC")
    else
      redirect_to new_session_path
    end
  end

  def task_params
    params.require(:task).permit(:title, :details, :priority, :status, :limit, :user_id, label_ids: [] )
  end
end

app/views/tasks/_form.html.erb
<div class="container">
  <%= form_with(model: @task, local: true) do |f| %>
    <% if @task.errors.any? %>
      <div id="error_explanation">
        <h2><%= @task.errors.count %>件のエラーがあります。</h2>
        <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="task_priority">
      <%= f.label :priority %>
      <%= f.select :priority, [["A", "A"],["B", "B"],["C", "C"],["D", "D"],["E", "E"]] %>
    </div>
    <div class="task_status">
      <%= f.label :status %>
      <%= f.select :status, [["未着手", "未着手"],["着手中", "着手中"],["完了", "完了"]] %>
    </div>
    <div class="task_title">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="task_details">
      <%= f.label :details %>
      <%= f.text_area :details %>
    </div>
    <div class="task_limit">
      <%= f.label :limit %>
      <%= f.date_select :limit, {} %>
    </div>
    <div class="task_label">
    <% label_list.each do |label| %>
      <% if action_name == 'new' || action_name == 'create' %>
        <%= f.check_box :label_ids, { multiple: true, checked: label[:checked], disabled: label[:disabled], include_hidden: false}, label[:id], "" %>
        <label><%= label.label_type %></label>
      <% elsif action_name == 'edit' || action_name == 'update' %>
        <%= f.check_box :label_ids, { multiple: true, checked: @task.label_ids.include?(label.id), disabled: label[:disabled], include_hidden: false}, label[:id], "" %>
        <label><%= label.label_type %></label>
      <% end %>
    <% end %>
    </div>
    <%= f.submit %>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<h1>タスク編集</h1>
<%= render 'form', task: @task %>
<%= link_to '戻る', tasks_path %>

app/views/tasks/index.html.erb
<div class="container-lg">
  <h1>タスク一覧</h1>
  <p>
    <span><%= link_to 'タスク新規登録', new_task_path %></span>
    <span><%= link_to 'ラベル新規登録', new_label_path %></span>
  </p>

  <%= form_with(model: @tasks, url:sort_tasks_path, method: :get, local: true) do |f| %>
    <%= f.label t('.title_search') %>
    <%= f.text_field :title %>
    <%= f.label t('.status_search') %>
    <%= f.select :status, [["未着手", "未着手"],["着手中", "着手中"],["完了", "完了"]], :include_blank => true %>
    <%= f.label t('.label_search') %>
    <%= f.collection_select :label_id, label_list, :id, :label_type, include_blank: true %>
    <%= f.submit "検索" %>
  <% end %>

  <ul class="list-group list-group-horizontal text-center">
    <li class="list-group-item flex-fill" style="border:none;"><%= link_to t('.tasks_limit_desc'), sort_tasks_path(sort_limit_desc: "true") %></li>
    <li class="list-group-item flex-fill" style="border:none;"><%= link_to t('.tasks_priority_asc'), sort_tasks_path(sort_priority_asc: "true") %></li>
  </ul>

  <div class="table-responsive">
    <table class ="table table-sm text-center table-striped">
      <thead class="thead-dark">
        <tr>
          <th scope="col">ラベル</th>
          <th scope="col">タスク名</th>
          <th scope="col">終了期限</th>
          <th scope="col">優先度</th>
          <th scope="col">ステータス</th>
          <th scope="col">担当</th>
          <th scope="col">編集</th>
          <th scope="col">削除</th>
        </tr>
      </thead>
      <tbody>
        <% @tasks.each do |task| %>
          <tr class=".tasks">
            <td class="align-middle">
              <% task.labellings.each do |label_type| %>
                <%= label_type.label.label_type %><br>
              <% end %>
            </td>
            <td class="align-middle"><%= link_to task.title, task %></td>
            <td class="align-middle"><%= task.limit %></td>
            <td class="align-middle"><%= task.priority %></td>
            <td class="align-middle"><%= task.status %></td>
            <td class="align-middle"><%= task.user.name %></td>
            <td class="align-middle"><%= link_to '編集', edit_task_path(task) %></td>
            <td class="align-middle"><%= link_to '削除', task, method: :delete, data: { confirm: t('.delete_confirm') } %></td>
          </tr>
        <% end %>
      <tbody>
    </table>
  </div>
  <%= paginate @tasks %>
</div>

app/views/tasks/new.html.erb
<h1>タスク新規登録</h1>
<%= render 'form' %>
<%= link_to '戻る', tasks_path %>

app/views/tasks/show.html.erb
<div class="container">
  <h1>タスク詳細</h1>
  <div class ="table-responsive">
    <table class="table table-sm text-center">
      <tr>
        <td class="bg-dark text-light">タスク名</td>
      </tr>
      <tr>
        <td><%= @task.title %></td>
      </tr>
      <tr>
        <td class="bg-dark text-light">タスク詳細</td>
      </tr>
      <tr>
        <td><%= @task.details %></td>
      </tr>
      <tr>
        <td class="bg-dark text-light">終了期限</td>
      </tr>
      <tr>
        <td><%= @task.limit %></td>
      </tr>
      <tr>
        <td class="bg-dark text-light">ラベル</td>
      </tr>
      <tr>
        <td>
          <% @task.labels.each do |label| %>
            <%= label.label_type %>
          <% end %>
        </td>
      </tr>
    </table>
  </div>
</div>

<div><%= link_to '編集', edit_task_path %></div>
<div><%= link_to '戻る', tasks_path %></div>