config/routes.rb
Rails.application.routes.draw do
  get 'labels/index'
  get 'sessions/new'
  root 'tasks#index'
  resources :tasks do
    collection do
      get :sort
    end
  end
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  namespace :admin do
    resources :users
  end

  resources :labels
end

app/models/label.rb
class Label < ApplicationRecord
  validates :label_type, presence: true
  has_many :labellings, dependent: :destroy, foreign_key: 'label_id'
  has_many :tasks, through: :labellings, source: :task

  belongs_to :user, optional: true
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_label, only: [:edit, :update, :destroy]

  def index
    @labels = Label.where(user_id: current_user.id)
    @labels_default = Label.where(user_id: nil)
  end

  def new
    if logged_in?
      @label = Label.new
    else
      redirect_to new_session_path
    end
  end

  def create
    @label = Label.new(label_params)
    @label.user_id = current_user.id
    if @label.save
      redirect_to labels_path
      flash[:success] = "ラベルを作成しました"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @label.update(label_params)
      redirect_to labels_path
      flash[:success] = "ラベルを編集しました"
    else
      render :edit
    end
  end

  def destroy
    @label.destroy
    redirect_to labels_path
    flash[:sucess] = "ラベルを削除しました"
  end

  private

  def set_label
    @label = Label.find(params[:id])
  end

  def label_params
    params.require(:label).permit(:label_type, :user_id)
  end
end

app/helpers/labels_helper.rb
module LabelsHelper
  def label_list
    Label.where("user_id is null or user_id = ?", current_user.id)
  end
end

app/views/labels/_form.html.erb
<div class="container">
  <%= form_with(model: @label, local: true) do |f| %>
    <% if @label.errors.any? %>
      <div id="error_explanation">
        <h2><%= @label.errors.count %>件のエラーがあります。</h2>
        <ul>
        <% @label.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="label_type">
      <%= f.label t('.label_type') %>
      <%= f.text_field :label_type %>
    </div>
    <%= f.submit %>
  <% end %>
</div>

app/views/labels/edit.html.erb
<h1>ラベル編集</h1>
<%= render 'form' %>
<%= link_to '戻る', labels_path %>

app/views/labels/index.html.erb
<div class="container-lg">
  <h1>ラベル一覧</h1>
  <p>
    <span><%= link_to 'タスク新規登録', new_task_path %></span>
    <span><%= link_to 'ラベル新規登録', new_label_path %></span>
  </p>
  <div class="table-responsive">
    <table class ="table table-sm text-center table-striped">
      <thead class="thead-dark">
        <tr>
          <th>自作ラベル</th><th>編集</th><th>削除</th>
        </tr>
      </thead>
      <tbody>
      <% @labels.each do |l| %> 
        <tr>
          <td><%= l.label_type %></td>
          <td><%= link_to '編集', edit_label_path(l) %></td>
          <td><%= link_to '削除', l, method: :delete, data: { confirm: "ラベルを削除しますか？" } %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <hr>
  <div class="table-responsive">
    <table class ="table table-sm text-center table-striped">
      <thead class="thead-dark">
        <tr>
          <th colspan="3">デフォルトラベル(編集・削除は出来ません)</th>
        </tr>
      </thead>
      <tbody>
      <% @labels_default.each do |label_d| %> 
        <tr>
          <td><%= label_d.label_type %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/labels/new.html.erb
<h1>ラベル新規登録</h1>
<%= render 'form' %>
<%= link_to '戻る', labels_path %>