config/routes.rb
Rails.application.routes.draw do
  get 'labels/index'
  get 'sessions/new'
  root 'tasks#index'
  resources :tasks do
    collection do
      get :sort
    end
  end
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  namespace :admin do
    resources :users
  end

  resources :labels
end

app/models/admin/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: true
  before_validation { email.downcase! }
  before_destroy :do_not_destroy_last_one_admin
  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }
  has_many :tasks, dependent: :destroy
  has_many :labels, dependent: :destroy

  private

  def do_not_destroy_last_one_admin
    if self.admin? && User.where(admin: :true).count == 1
      throw :abort
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :ensure_current_user_admin
  before_action :set_users, only: [:show, :destroy, :edit, :update]
  before_action :before_destroy, only: [:destroy]

  def index
    @users = User.all.includes(:tasks).order(id: "ASC")
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
       redirect_to tasks_path
       flash[:info] = "#{@user.name}さんのアカウントを作成しました"
    else
      render :new
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path
    flash[:success] = 'アカウントを削除しました'
  end

  def show
  end

  def edit
  end

  def update
    @user.update(user_params)
    if User.where(admin: :true).count == 0
      @user.update(admin: :true)
      redirect_to admin_users_path
      flash[:warning] = "ユーザー【 #{@user.name} 】の権限以外を更新しました　※管理者は最低一人必要です"
    elsif @user.save == false
      flash[:danger] = "ユーザー情報の更新が出来ませんでした"
      render :edit
    elsif User.where(admin: :true).count >= 1
      redirect_to admin_users_path
      flash[:info] = "ユーザー【 #{@user.name} 】の更新をしました"
    end
  end

  private

  def ensure_current_user_admin
    if logged_in? == false
      redirect_to new_session_path
      flash[:danger] = "ログインしてください"
    elsif current_user.admin? == false
      redirect_to tasks_path
      flash[:danger] = "管理者権限がありません"
    end
  end

  def before_destroy
    if @user.admin == true && @user == current_user
      redirect_to admin_users_path
      flash[:danger] = "管理者自身は削除できません" 
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_current_user, only: [:show]
  before_action :set_users, only: [:show]

  def new
    if logged_in? 
      redirect_to tasks_path
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
       session[:user_id] = @user.id
       redirect_to user_path(@user.id)
       flash[:info] = "#{@user.name}さんのアカウントを作成しました"
    else
      render :new
    end
  end

  def show
  end

  private

  def ensure_current_user
    if logged_in? == false
      redirect_to new_session_path
      flash[:danger] = "ログインしてください"
    elsif current_user.id != params[:id].to_i
      redirect_to tasks_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper

  private

  def set_users
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
  end
end

app/views/admin/users/_form.html.erb
<%= form_with(model: [:admin, @user], local: true) do |f| %>
  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "件のエラーがあります。") %></h2>
    <ul>
    <% @user.errors.full_messages.each do |m| %>
      <li><%= m %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <% if current_user.admin? %>
    <%= f.label :admin %>
    <%= f.select :admin, [["一般", false],["管理者", true]]%>
  <% end %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit %>
<% end %>

app/views/admin/users/edit.html.erb
<h1>ユーザー編集ページ</h1>

<%= render 'form' %>

app/views/admin/users/index.html.erb
<h1>管理画面のユーザー一覧</h1>
<div class="container">
  <div class="table-responsive">
    <table class ="table table-sm text-center table-striped">
      <thead class="thead-dark">
        <tr scope="col">
          <th>ユーザーID</th>
          <th>ユーザー名(太字：管理者)</th>
          <th>タスク数</th>
          <th>権限</th>
          <th>削除</th>
        </tr>
      </thead>
      <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <% if user.admin? %>
            <td style="font-weight:bold;"><%= user.name %></td>
          <% else %>
            <td><%= user.name %></td>
          <% end %>
          <td><%= user.tasks.size %></td>
          <td><%= link_to '編集', edit_admin_user_path(user) %></td>
          <td><%= link_to '削除',[:admin, user], method: :delete, data: { confirm: 'このアカウントを削除しますか？' } %></td>
        </tr>
      <% end %>
      <tbody>
    </table>
  </div>
</div>

app/views/admin/users/new.html.erb
<h1>アカウント新規作成</h1>

<%= render 'form' %>

app/views/admin/users/show.html.erb
<h1>ユーザーページ</h1>

<ul>
  <li><%= @user.name %></li>
  <li><%= @user.email %></li>
  <% if @user.admin? %>
    <li>管理者</li>
  <% else %>
    <li>一般ユーザー</li>
  <% end %>
</ul>

<% if current_user.admin? %>
  <div class="table-responsive">
    <table class ="table table-sm text-center table-striped">
      <thead class="thead-dark">
        <tr>
          <th scope="col">ラベル</th>
          <th scope="col">タスク名</th>
          <th scope="col">終了期限</th>
          <th scope="col">優先度</th>
          <th scope="col">ステータス</th>
          <th scope="col">担当</th>
          <th scope="col">編集</th>
          <th scope="col">削除</th>
        </tr>
      </thead>
      <tbody>
        <% @user.tasks.each do |task| %>
          <tr class = ".tasks">
            <td>※後ほど実装</td>
            <td><%= task.title%></td>
            <td><%= task.limit %></td>
            <td><%= task.priority %></td>
            <td><%= task.status %></td>
            <td><%= @user.name %></td>
            <td><%= link_to '編集', edit_task_path(task) %></td>
            <td><%= link_to '削除', task, method: :delete, data: { confirm: '本当に削除してもよろしいですか？' } %></td>
          </tr>
        <% end %>
      <tbody>
    </table>
  </div>
<% end %>