config/routes.rb
Rails.application.routes.draw do
  get 'labels/index'
  get 'sessions/new'
  root 'tasks#index'
  resources :tasks do
    collection do
      get :sort
    end
  end
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  namespace :admin do
    resources :users
  end

  resources :labels
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OwntaskApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <header>
    <h1 class="bg-dark text-white py-1"><%= link_to 'Owntask', tasks_path %></h1>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>">
        <%= message %>
      </div>
    <% end %>
  </header>
    <% if logged_in? %>
      <%= current_user.name %>
      <%= link_to t('.user_page'), user_path(current_user.id) %>：
      <% if current_user.admin? %>
        <%= link_to t('.user_manage'), admin_users_path %>：
        <%= link_to t('.new_account'), new_admin_user_path %>：
      <% end %>
      <%= link_to t('.label_list'), labels_path %>：
      <%= link_to t('.logged_out'), session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to t('.new_account'), new_user_path %>：
      <%= link_to t('.logged_in'), new_session_path %>
    <% end %>
    <%= yield %>
  </body>
  <footer class="footer mt-auto py-3 bg-dark text-white">
    © yuhki.ikeda
  </footer>
</html>